package io.github.zskamljic.restahead.demo;

import io.github.zskamljic.restahead.adapter.DefaultAdapters;
import io.github.zskamljic.restahead.client.Response;
import io.github.zskamljic.restahead.client.RestClient;
import io.github.zskamljic.restahead.client.requests.DeleteRequest;
import io.github.zskamljic.restahead.exceptions.RestException;
import java.io.IOException;
import java.lang.InterruptedException;
import java.lang.Override;
import java.util.concurrent.ExecutionException;
import javax.annotation.processing.Generated;

@Generated("Generated by RestAhead")
public final class InterfaceWithThrows$Impl implements InterfaceWithThrows {
    private final RestClient client;

    private final DefaultAdapters defaultAdapters;

    public InterfaceWithThrows$Impl(RestClient client, DefaultAdapters defaultAdapters) {
        this.client = client;
        this.defaultAdapters = defaultAdapters;
    }

    @Override
    public final Response delete() throws IOException {
        var httpRequest = new DeleteRequest("/delete");
        var response = client.execute(httpRequest);
        try {
            return defaultAdapters.syncAdapter(response);
        } catch (ExecutionException | InterruptedException exception) {
            throw RestException.getAppropriateException(exception);
        }
    }
}
